### ISSUE TITLE
Error org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping

### ISSUE THREAD

**Issue by lospejos** [FlyFunMan/custom-ores#1]
When plugin `Custom Ores` version 4.1 is installed on server, no ores configured, when server starts, error message in log appears:

```
[12:57:10 INFO]: [CustomOres] Enabling CustomOres v4.1
[12:57:10 ERROR]: Cannot load configuration from stream
org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in 'reader', line 1, column 1:
    Config Warning: 'Explanation for ...
    ^
expected <block end>, but found '<scalar>'
 in 'reader', line 75, column 22:
    No Items: 'You haven't created any items yet!'
                         ^

        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:105) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:334) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at me.flyfunman.customos.Main.loadLang(Main.java:196) ~[CustomOres.jar:?]
        at me.flyfunman.customos.Main.onEnable(Main.java:46) ~[CustomOres.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:611) ~[purpur-1.19.2.jar:git-Purpur-1819]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:525) ~[purpur-1.19.2.jar:git-Purpur-1819]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.19.2.jar:git-Purpur-1819]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427) ~[purpur-1.19.2.jar:git-Purpur-1819]        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:343) ~[purpur-1.19.2.jar:git-Purpur-1819]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.19.2.jar:git-Purpur-1819]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1819]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'reader', line 1, column 1:
    Config Warning: 'Explanation for ...
    ^
expected <block end>, but found '<scalar>'
 in 'reader', line 75, column 22:
    No Items: 'You haven't created any items yet!'
```

In your file `lang.yml` you incorrectly used a single quote, probably, you'll have to mask it somehow. Or use double quoted string. Or use full form of `have not` instead of `haven't` to avoid using single quote inside single-quoted string.

**Comment by FlyFunDev** [comment]
Alright, I switched it to `have not`. Thank you for reporting this.
